GHANA_REGIONS = [
    ("greater_accra", "Greater Accra"),
    ("ashanti", "Ashanti"),
    ("western", "Western"),
    ("western_north", "Western North"),
    ("central", "Central"),
    ("eastern", "Eastern"),
    ("volta", "Volta"),
    ("oti", "Oti"),
    ("northern", "Northern"),
    ("savannah", "Savannah"),
    ("north_east", "North East"),
    ("upper_east", "Upper East"),
    ("upper_west", "Upper West"),
    ("bono", "Bono"),
    ("bono_east", "Bono East"),
    ("ahafo", "Ahafo"),
]
